-- ============================================================
-- BUTTE STRONG WELLNESS — Seed Data
-- Run AFTER schema.sql in the Supabase SQL Editor
-- ============================================================

-- ── PEER SUPPORT MEMBERS ─────────────────────────────────────
insert into peer_support_members (name, agency, phone, email, bio, experience, is_chaplain, sort_order) values
('Aaron Parmley',          'BCSO',     '209-534-2616', 'Parmley.aaron@gmail.com',        'I started in the Butte County Jail in 2015. In 2017 I moved out to patrol. A majority of my patrol time has spent in the Magalia area.',                                                                                                                                                                                                                                                                                                                                                                             'In the first 5 years in your career, Experienced a critical incident',                                                                                                             false, 1),
('Alex Duenas',            'BCPD',     '916-899-8160', 'aduenas@buttecounty.net',         'I have worked with the Butte County Probation Department for 11 years and have seen what this type of work can do to us who work in this field. I want everyone to be healthy and well and to be the best version of themselves, being as healthy as they can not only for those they serve, but most importantly, their families and their life outside of work.',                                                                                                                                                       'In the first 5 years in your career, Parenting, Finances, Substance use in your family, Mental health in your family, Injury',                                                     false, 2),
('Alyssa Varao',           'CPD',      '530-415-8894', 'Alyssa.varao@chicoca.gov',        'I am a dedicated public service professional with a background in healthcare and law enforcement support. I spent five years working as a Certified Medical Assistant after completing my technical college training. I currently serve as a Community Service Officer, where I have taken on additional responsibilities including acting as a TLO, supporting the Chico Police Department recruitment team, and managing operations for our temporary holding facility. I am a mother of two children and value spending time outdoors with my family.', 'Divorce and family transitions, Mental health within the family, Parenting and child development, Parenting a child with special needs, Substance use within the family',          false, 3),
('Andrea Lui',             'PPD',      '530-588-5168', 'turenneandrea@gmail.com',         'I have served the Paradise community with Paradise Police Department for 8 years. 6 years as a Police Dispatcher and 2 years as an Administrative Assistant. I have always been a believer in peer support and of prioritizing mental health. Due to my interest in mental health, I completed a Bachelors Degree in Psychology. I am excited to be a part of this program.',                                                                                                                                             'In the first 5 years in your career, Parenting, Substance use in your family, Mental health in your family',                                                                       false, 4),
('Bill Kolb',              'CSPD',     '530-923-1520', 'wkolb@csuchico.edu',              'I have been a police officer with the CSU, Chico Police Department since 2007. I am currently a patrol sergeant and I previously was a detective with the department for several years. I became interested in peer support/wellness after learning about the effects of stress and hyper vigilance on the lives of first responders.',                                                                                                                                                                                    'In the first 5 years in your career, Lifelong career (over 15 years), Parenting, Finances',                                                                                        false, 5),
('Chris O''Meara',         'BEMS',     '510-735-4511', 'chris.om2010@gmail.com',          'I have been a first responder for the past 7 years. I have been working as a Paramedic in Butte County for the last two.',                                                                                                                                                                                                                                                                                                                                                                                             'In the first 5 years in your career, Lifelong career (over 15 years), Experienced a critical incident, Experienced an OIS, Finances, Substance use in your family, Mental health in your family, Injury', false, 6),
('Christopher B. Nicodemus','CSPD',   '530-570-8743', 'cnicodemus@csuchico.edu',         'I have been in law enforcement for 22 years and worked for the Oroville Police Department, Butte County Sheriff''s Office and California State University, Chico Police Department. I also teach at the Butte College Law Enforcement Academy. I have seen first hand the importance of improving the peer support and wellness program at my agency and those agencies I previously worked for.',                                                                                                                           'Lifelong career (over 15 years), Experienced a critical incident, Experienced an OIS, Parenting',                                                                                  false, 7),
('Dan Hornyak',            'BEMS',     '530-434-8054', 'Djyak74@gmail.com',               'Lifelong career as a Firefighter/EMT, current EMS, military veteran, serving all over the world. I support wellness not only for myself and family, but for my fellow coworkers.',                                                                                                                                                                                                                                                                                                                                      'In the first 5 years in your career, Lifelong career (over 15 years), Parenting, Divorce, Finances, Mental health in your family, Injury',                                         false, 8),
('Gina Marr',              'UPD',      '530-370-6701', 'Ginamarr@live.com',               'I''ve worked in law enforcement for almost 30 years in different agencies including the District Attorneys Office, Superior Court, Oroville Police Dept. and currently Chico State Police. I decided to get involved in Peer support to help others going through experiences that I''ve gone through but didn''t have any resources of support.',                                                                                                                                                                      'In the first 5 years in your career, Lifelong career (over 15 years), Experienced a critical incident, Experienced an OIS, Parenting, Divorce',                                   false, 9),
('Jason Behlke',           'BCSO',     '530-228-4434', 'Jbehlke@buttecounty.net',         'I have worked in Butte County Corrections in many capacities for the last 16 years. In those years I have worked through many critical incidents. I would love to share my coping skills to aid in working through these trying and lasting events.',                                                                                                                                                                                                                                                                   'In the first 5 years in your career, Lifelong career (over 15 years), Experienced a critical incident, Experienced an OIS, Injury',                                                false, 10),
('Jeannette Huggins',      'PPD',      '530-519-6633', 'jeannettehuggins23@gmail.com',    'I''ve worked with Paradise PD for 6 years. I started as a dispatcher and I am now the Support Services Supervisor overseeing dispatch, records and property/evidence. I have my BA in Psychology and I am very excited to put that to more use with Peer Support.',                                                                                                                                                                                                                                                      'Experienced a critical incident, Parenting, Substance use in your family, Mental health in your family',                                                                            false, 11),
('Jennifer Alton',         'BCSO',     '720-212-6035', 'JAlton@buttecounty.net',          'I have worked for the Butte County Sheriff''s Office for 7 years in the capacity of a Training Coordinator/Clerk III. I was part of the support staff during the Oroville Spillway/Dam incident, and worked the Missing Persons hotline during the Camp Fire and served as a liaison for the EOC during the Complex Fire.',                                                                                                                                                                                             'Experienced a critical incident, Parenting, Divorce',                                                                                                                              false, 12),
('Jennifer Honea',         'BCSO',     '530-514-4044', 'jhonea@buttecounty.net',          'I am the Dispatch Supervisor, and I am approaching my 27th year with BCSO. During my career I have experienced many difficult incidents and situations. Peer support was not available or an option. I would like to make a positive impact of employees throughout their career.',                                                                                                                                                                                                                                      'In the first 5 years in your career, Lifelong career (over 15 years), Experienced a critical incident, Experienced an OIS, Parenting, Finances, In the line of duty death of a family member', false, 13),
('Jeremy Gagnebin',        'CPD',      '530-514-3110', 'Jgagnebin11@gmail.com',           'I have been a police officer since December 2015. Within my first two years of service, I was involved in and present at two separate officer involved shootings. I became interested in peer support after seeing the positive change it can have in one''s life, both at and outside of work.',                                                                                                                                                                                                                        'Experienced a critical incident, Experienced an OIS, Parenting, Finances, Substance use in your family',                                                                           false, 14),
('Joel Gist',              'CPD',      '559-676-9274', 'joel.gist@chicoca.gov',           'Joel Gist has a Bachelor''s Degree in Liberal Studies from Fresno Pacific University and a Master''s Degree in Organizational Leadership from Gonzaga University. Prior to becoming a Chico Police Officer in 2021, Joel served as Director of Operations and Program Director at Calvin Crest Conferences near Yosemite, CA.',                                                                                                                                                                                          null,                                                                                                                                                                                false, 15),
('John Nickelson',         'CPD',      '530-720-3744', 'john.nickelson@chicoca.gov',      'I have been a police officer since February 2012. In my first 4 years of being a police officer, I was involved in 2 shootings, one of which my partner was hit. I became interested in officer wellness due to the care that my fellow colleagues showed me, and from support I received through Butte County Critical Incident Stress Management.',                                                                                                                                                                     'Experienced a Critical Incident',                                                                                                                                                   false, 16),
('Ken Smith',              'CFD',      '530-624-2922', 'ken.smith@chicoca.gov',           'Been in the fire service 30 years — 26 years with Chico Fire as a volunteer and career Firefighter. I have a true passion for peer support and promoting a positive vibe in the often negative environment that we serve in. My personal goal is to help others have a healthy balance of work and play, while putting family first.',                                                                                                                                                                                    'Lifelong career (over 15 years), Experienced a critical incident, Parenting, Finances, Substance use in your family, Mental health in your family, Injury',                         false, 17),
('Kevin Tuck',             'PPD',      '530-682-0284', 'ktuck@townofparadise.com',        'I started my Law Enforcement career in 2010 and have been in Search and Rescue, Corrections, and Patrol. Currently I am a Patrol Officer in Paradise. I appreciate the camaraderie in Law Enforcement and have always enjoyed helping others through their rough times, even if they just need to vent to someone.',                                                                                                                                                                                                     'Lifelong career (over 15 years), Experienced a critical incident, Parenting, Divorce, Finances, Substance use in your family, Mental health in your family',                        false, 18),
('Konoli Martin',          'CAL FIRE', '530-538-7111', 'konolimartin@gmail.com',          '26th Fire Season — Cal Fire / Butte County Fire. 4 years in Peer Support. My passion for peer support is to educate new employees on mental health and providing the tools for self-care.',                                                                                                                                                                                                                                                                                                                             'In the first 5 years in your career, Lifelong career (over 15 years), Divorce, Mental health in your family, Injury',                                                              false, 19),
('Kristi Meyer',           'BCSO',     '530-228-2542', 'Kristi0073@yahoo.com',            'I have worked at the Sheriff''s Office 5 years and my husband has worked for the Sheriff''s Office for 20 years. I believe in building strong relationships with family and with co-workers because we deal with most people on the job on their worst days.',                                                                                                                                                                                                                                                           'In the first 5 years in your career, Parenting, Substance use in your family, Mental health in your family, Injury, Spouse also in Law enforcement',                               false, 20),
('Levi Bryant',            'BCSO',     '530-788-8713', 'kbryant@buttecounty.net',         'I have worked with the Butte County Sheriff''s Office for approximately 8 years. My assignments have included Patrol, FTO, and Firearms instruction.',                                                                                                                                                                                                                                                                                                                                                                  'In the first 5 years in your career, Experienced a critical incident, Experienced an OIS, Parenting, Finances, Substance use in your family',                                      false, 21),
('Loren Ferreira',         'CPD',      '530-570-1596', 'Loren.Ferreira@chicoca.gov',      '10+ years with Chico Police Department. Peer support and wellness are important to me because you need to be able to take care of yourself to take care of others during our scope of work.',                                                                                                                                                                                                                                                                                                                           'In the first 5 years in your career, Experienced a critical incident, Experienced an OIS, Illness in the family or self',                                                          false, 22),
('Mariah Smith',           'BCSO',     '916-218-0711', 'masmith@buttecounty.net',         'I''ve been a Deputy Sheriff for just under 7 years. I''ve worked patrol, investigations, and as a School Resource Deputy. I was involved in an OIS early on in my career and then was seriously injured at work during a separate incident. Peer Support and Mental Wellness helped me get through tough points in my life.',                                                                                                                                                                                            'In the first 5 years in your career, Experienced a critical incident, Experienced an OIS, Work related injury and trauma',                                                         false, 23),
('Meghan McKone',          'BCSO',     '530-588-3682', 'mmckone2017@gmail.com',           'Working as a first responder for over 3 years as a 911 dispatcher with the Butte County Sheriff''s Office. Sometimes you need someone who "gets it" and just be able to vent or talk something through.',                                                                                                                                                                                                                                                                                                               'In the first 5 years in your career, Experienced a critical incident, Parenting, Substance use in your family, Mental health in your family',                                       false, 24),
('Melody Brown',           'BEMS',     '530-720-7503', 'Mbrown@bcems.org',                'I have been in and around EMS since 2004. I started my 911 career with Butte County EMS in 2007 and have been a paramedic since 2008. I worked as a paramedic and field training officer full-time until 2017 when I also took on the role of Health and Safety Officer. Now I am the Deputy Chief of Operations and HR.',                                                                                                                                                                                              'In the first 5 years in your career, Lifelong career (over 15 years), Experienced a critical incident, Mental health in your family, Injury',                                      false, 25),
('Michele Meador',         'BCSO',     '530-518-1535', 'Mmeador@buttecounty.net',         'Happy to chat about anything! Have been in dispatch since 2018. Have experience not only personally but am also a spouse to a first responder so I can understand both dynamics.',                                                                                                                                                                                                                                                                                                                                      'Experienced a critical incident, Parenting, Mental health in your family, Injury',                                                                                                  false, 26),
('Miranda Pierce',         'CPD',      '916-947-0356', 'miranda.pierce@chicoca.gov',      'Officer with the Chico Police Department for approximately 6 years. Currently a Detective. My background is in Psychology and Behavioral Analysis. Family comes first with me and I enjoy helping those around me to get home safely to theirs.',                                                                                                                                                                                                                                                                        'In the first 5 years in your career, Experienced a critical incident, Parenting, Divorce, Loss of spouse, Mental health in your family',                                            false, 27),
('Shelley Keener',         'CSPD',     '530-521-3947', 'skeener@csuchico.edu',            'I started my law enforcement career in 2008 as a dispatcher for Corning Police Department. During that time I was able to participate in a multi-agency child abduction task force and also work as a tactical dispatcher. I began working at Chico State PD in 2017 as the Communications, Records, and Property Specialist.',                                                                                                                                                                                         'Lifelong career (over 15 years), Experienced a critical incident, Dispatch/Support Services',                                                                                      false, 28),
('Thomas Cox',             'CPD',      '858-699-5542', 'Thomas.cox@chicoca.gov',          'I have been a Police Officer since 2015. Peer support has been a part of my career since my academy days and I have seen firsthand how it can help first responders and their families throughout this career.',                                                                                                                                                                                                                                                                                                         'Police officer experience',                                                                                                                                                         false, 29),
('Trenton Eidhammer',      'PPD',      '530-520-1538', 'Eidhammer53@gmail.com',           'I am Trenton Eidhammer. I have been in law enforcement for 1 year. Prior to law enforcement I spent 5 years as a firefighter. Peer support is important to me because we have all been through something and you never know when someone will experience the same thing.',                                                                                                                                                                                                                                               'In the first 5 years in your career, Experienced a critical incident, Substance use in your family, Mental health in your family, Injury',                                          false, 30),
('Wes Metroka',            'CFD',      '530-828-2141', 'wesley.metroka@chicoca.gov',      'I''ve been in the fire service for 24 years and am currently a Battalion Chief with the Chico Fire Department. My career began with Cal Fire in the Shasta/Trinity Unit. After two seasons with the state, I took a position with my hometown Paradise Fire Department. I look at Peer Support team members as a "concierge" for mental health and wellness resources.',                                                                                                                                                   'Lifelong career (over 15 years), Experienced a critical incident, Parenting, Divorce',                                                                                             false, 31),
-- Chaplains
('Chaplain Ed Hall',       'BCSO',     '530-990-5622', 'ehall@buttecounty.net',           'Edward Hall became the Senior Chaplain for Butte County Sheriff''s Office in 2017 and serves as Senior Pastor of Wynn Memorial Church in Oroville. He previously served with the US Navy for six years during the Desert Storm Era. Certifications include CISM, Suicide Prevention, Death Notification, Officer Involved Shooting Debrief, and EMDR Level 1. He served as team leader for CARE during the Camp Fire (2018–2019).',                                                                                     'Lead Chaplain · BCSO · Critical Incident Stress Management Team',                                                                                                                  true,  1),
('Chaplain Ken Malone',    'BCSO',     '530-282-3313', null,                              'Chaplain Ken Malone has been the Pastor of New Life Church in Oroville for 24 years and currently serves as a Chaplain for BCSO. Born in Denver, Colorado, he moved to Oroville in 1976. He loves his family, the outdoors, fishing, hunting, and camping.',                                                                                                                                                                                                                                                           'BCSO Chaplain',                                                                                                                                                                     true,  2),
('Chaplain Josh Cook',     'BCSO',     null,           'jcook@buttecounty.net',           'Chaplain Josh Cook was sworn in as a BCSO Chaplain in March 2022. He served 9 years in the California State Guard, attaining the rank of Staff Sergeant. He is ordained in The Church of Jesus Christ of Latter-day Saints and is an Associate Professor at the University of Southern California Price School of Public Policy. His areas of expertise include marriage and family counseling, emergency management, disaster recovery, and response to moral injury and trauma.',                                        'BCSO Chaplain · Marriage & Family Counseling · Emergency Management · Trauma Response',                                                                                            true,  3),
('Chaplain Brian Dudar',   'BCSO',     '530-520-4112', 'bdudar@buttecounty.net',          'Brian Dudar spent 11 years in youth ministry, along with 13 years as an Army Chaplain ministering to combat and hospital units. He received his Master''s in Divinity from Andrews University in 1993. He currently serves as the Dental Director of Northern Valley Indian Health. He joined BCSO as a chaplain in May 2017 and was involved in chaplain coverage during the Camp Fire.',                                                                                                                                'BCSO Chaplain · Army Chaplain · Suicide Prevention · Critical Incident Counseling · Trauma',                                                                                       true,  4);


-- ── THERAPISTS ────────────────────────────────────────────────
insert into therapists (name, title, phone, email, address, insurance, bio, quote, sort_order) values
('Sesha Zinn, PsyD',                   'Licensed Clinical Psychologist',        null,            null,                               'Virtual (online platform)',                           'Aetna, Anthem Blue Cross CA, Blue Shield of CA, Cigna, Kaiser Permanente of Northern CA, Oscar Health, Oxford, United Healthcare', 'Dr. Sésha Zinn is a California Licensed Clinical Psychologist with 20 years of experience working in Butte County directly with first responders, youth and families. She currently leads the CARE Team and specializes in trauma and family dynamics.',                                                                                                                                     'Our community has suffered greatly, and our first responders have experienced it all firsthand. We all wish for you first and foremost to serve and protect yourselves and those you love by reaching out for support when you or your family need it.', 1),
('Josh Ascherman, PsyD, MA, MPA',      'Licensed Marriage & Family Therapist',  '530-413-0032',  'Josh@chicocounselor.com',          '80 Independence Circle, #210, Chico',                 'Contact for details',                                                                                                                 'Josh Ascherman is a former Sheriff''s Deputy and Retired CHP Officer who has worked as and with first responders for 25 years. He has been on the providing and receiving ends of Critical Incident Stress Debriefings, combining his firsthand law enforcement and clinical experience. He is an affiliate therapist of the First Responder Support Network.',                                                                                   null, 2),
('Lisa Jellison, LCSW',                'Licensed Clinical Social Worker',        '530-228-6301',  'lisajellisonlcsw@sbcglobal.net',   '5 Governors Ln, Unit 150, Chico, CA 95926',           'Cash pay only · Superbill provided',                                                                                                  'Lisa Jellison has been a Licensed Clinical Social Worker since 1999 with over 30 years in the Mental Health field. She has extensive experience facilitating Critical Incident Stress Debriefings (CISD) and was previously the Manager of the Social Work Department at Enloe Health. Her mindset: you don''t need a mental health diagnosis to seek out counseling.',                                                                          null, 3),
('Chris Sims, LCSW',                   'Licensed Clinical Social Worker',        '530-431-8420',  'cmsimslcsw@gmail.com',             '5 Governors Lane, Suite 150, Chico, CA 95926',        'Medicare · Superbill provided',                                                                                                       'Chris Sims has been a California Licensed Clinical Social Worker and Therapist for more than 20 years. His work focuses on ending negative perceptions and establishing a more accurate understanding of both ourselves and our situations. He specializes in men''s issues and anger management.',                                                                                                                                                 null, 4),
('Tami Keeney, LMFT',                  'Licensed Marriage & Family Therapist',  '530-433-9061',  'tami@northvalleycounseling.com',   '260 Cohasset Rd, Suite 120, Chico, CA 95926',         'Cash pay only · Superbill provided · Discount for extended sessions',                                                                 'Tami Keeney has been a Licensed Marriage Family Therapist since 2005 and is trained in EMDR, TF-CBT, and play therapy. Her husband has been with Chico Police Department for over 26 years as a Captain — she fully understands the challenges and stressors that accompany being a first responder family.',                                                                                                                                     null, 5),
('Patricia Long, LMFT',                'Licensed Marriage & Family Therapist',  '530-685-8048',  'patricialong72.pl@gmail.com',      '40 Constitution Dr C, Chico, CA 95973',               'EAP: Claremont & Magellan · Private pay · Superbill provided',                                                                        'Patricia Long has 11 years working as a mental health clinician. She works in private practice with first responders and their families. Her husband of 20+ years is a Sergeant for Butte County Sheriff''s Office. She deeply understands the impact of trauma that first responders experience, through her therapy work and personally.',                                                                                                        null, 6),
('Kirsten Storne-Piazza, MA, LMFT, CRHCP', 'Licensed Marriage & Family Therapist', '530-370-1802', 'kstorne@orchardhospital.com',  '240 Spruce St., Gridley, CA 95948',                    'Contact for details',                                                                                                                 'Kirsten Storne-Piazza was born into a law enforcement family and has 20 years'' experience working with first responders. Her husband currently serves as a sergeant for the Butte County Sheriff''s Office. She joined the Butte-Glenn Critical Incident Stress Management team 8 years ago and has been working primarily with first responders since the Camp Fire.',                                                                           null, 7);


-- ── TEAM MEMBERS ──────────────────────────────────────────────
insert into team_members (name, role, agency, email, phone, bio, accent, sort_order) values
('Jodi Drysdale', 'Wellness Unit Manager', 'BCSO', 'jdrysdale@buttecounty.net', '530-321-8429',
 'Jodi Drysdale has been the Wellness Unit Manager since 2021. Jodi has a Bachelor''s degree in Health Education and Community Service and previously spent six years working for the Butte County Dept. of Behavioral Health in the Community Services Division, Prevention Unit. For the past 15 years, Jodi has owned an event planning business volunteering her time planning events that honor and celebrate first responders — including the Camp Fire appreciation dinners and the Chico Firefighters Ball. In 2020, Jodi managed the Camp Fire Collaborative, coordinating partner agencies serving the long-term recovery of people affected by the Camp Fire.',
 '#C9A84C', 1),
('Mandy Barrow', 'Family Engagement Specialist', null, 'mandyjoybarrow@yahoo.com', '(949) 338-4553',
 'Mandy Barrow is married to Detective Cory Barrow of Chico PD and they have 3 children. Mandy assists Jodi with Wellness Unit events, meetings, and monthly newsletters.',
 '#1A8A72', 2),
('Wes Metroka', 'Advisory Committee · Battalion Chief', 'CFD', 'wesley.metroka@chicoca.gov', '530-828-2141',
 'I''ve been in the fire service for 24 years and am currently a Battalion Chief with the Chico Fire Department. My career began with Cal Fire in the Shasta/Trinity Unit. After two seasons with the state, I took a position with my hometown Paradise Fire Department. After 8 years in Paradise, I made the move to Chico Fire. Peer Support is one of the greatest wellness resources a fire department can promote and support.',
 '#2563A8', 3);


-- ── FITNESS CATEGORIES ────────────────────────────────────────
insert into fitness_categories (title, description, sort_order) values
('Fortified Physio — Physical Therapy', 'Free physical therapy for all Butte County first responder staff and volunteers.', 1),
('Brazilian Jiu Jitsu',                 'Drop-in BJJ training for sworn staff at multiple Butte County locations.', 2),
('Yoga 911',                            'Evidence-based yoga and meditation designed for first responders. Saturdays at 10:45 AM.', 3),
('Fight Forward Kickboxing',            'Open to all agency staff. Drop-in M–F. Cardio + strength training.', 4),
('Lord''s Gym — Oroville',             'Drop-in sessions for all agency staff in Oroville.', 5),
('Acupuncture',                         'Up to 4 covered sessions per year for all staff.', 6),
('North Rim CrossFit',                  'Free drop-in CrossFit classes for Butte County first responders.', 7),
('Elevate Health and Performance',      'CrossFit-style group fitness in Paradise. 6 daily class times.', 8),
('Perspire Sauna Studio',               'Private infrared sauna suites with red light therapy. Up to 8 sessions at no cost.', 9);


-- ── FITNESS ITEMS ─────────────────────────────────────────────
-- Fortified Physio (category 1)
insert into fitness_items (category_id, title, item_type, content, description, address, sort_order) values
(1, 'About the Service',   'info', 'Physical therapy through Fortified Physio is a free service offered to the staff and volunteers of all First Responding agencies in Butte County. Appointments are filled with detailed assessments, skilled treatments, and uninterrupted 1-on-1 sessions. Out-of-network PT is also available for spouses, kids, and other family at the Chico Clinic location.', null, null, 1);
insert into fitness_items (category_id, title, item_type, url, sort_order) values
(1, 'Schedule an Appointment', 'link', 'https://fortifiedphysio.janeapp.com/', 2);
insert into fitness_items (category_id, title, item_type, description, address, sort_order) values
(1, 'Chico Clinic', 'location', 'Available to ALL agency employees and volunteers.', '629 Entler Ave., #44, Chico, CA 95928', 3),
(1, 'BCSO — South County', 'location', 'Available to ALL agency employees and volunteers.', 'BCSO South County location', 4),
(1, 'Chico PD Location', 'location', 'Available to CPD staff and volunteers ONLY.', 'Chico PD facility', 5);
insert into fitness_items (category_id, title, item_type, content, sort_order) values
(1, 'About Dr. Kelsey Mosier PT, DPT, CF-L1', 'info', 'Dr. Kelsey Mosier was born and raised in Paradise, California, and received her Doctorate of Physical Therapy from South College in June 2020. Kelsey is the founder of Fortified Physio and is passionate about the population she serves. Her treatment approach includes skilled hands-on techniques and functional exercise. When Kelsey is outside of the clinic you can find her exploring the outdoors, at her local CrossFit gym, or hanging out with her husband and 3 dogs.', 6),
(1, 'About Dr. Michael Ellis PT, DPT, CERT-CMFA', 'info', 'Michael is a co-founder and physical therapist at Fortified Physio. He graduated from CSU Chico in 2014 with a bachelor''s degree in exercise physiology, then attended the University of the Pacific and graduated in 2017 with his Doctorate in Physical Therapy. Michael has completed an orthopedic residency and holds a Clinical Management of the Fitness Athlete certification. He practices Brazilian Jiu Jitsu and holds a blue belt.', 7);

-- BJJ (category 2)
insert into fitness_items (category_id, title, item_type, description, address, sort_order) values
(2, 'Cultivate Power Fighting Arts', 'location', 'BJJ classes open to sworn staff only.', '1790 Montgomery St., Oroville, CA 95965', 1),
(2, 'BJJ at Americana', 'location', 'Drop-in sessions for all sworn staff. Identify yourself as sworn LE staff when checking in.', '13306 Cabin Hallow Court, Suite 100, Chico', 2),
(2, 'BJJ at StandAlone MMA', 'location', 'Drop-in sessions for LE sworn staff. Identify yourself as sworn LE when checking in.', '849 W. 9th St., Chico', 3),
(2, 'Oroville BJJ Academy', 'location', 'Drop-in sessions for all sworn staff. Identify yourself as sworn LE when checking in.', '2020 Bird St., Oroville', 4);
update fitness_items set website = 'https://americanabjj.com/class-schedule/' where title = 'BJJ at Americana';
update fitness_items set website = 'https://www.standalonemma.com/schedule' where title = 'BJJ at StandAlone MMA';
update fitness_items set website = 'https://orovillejiujitsu.com/', hours = 'Mon · Tue · Thu · Fri — 7:00–8:30 PM' where title = 'Oroville BJJ Academy';

-- Yoga 911 (category 3)
insert into fitness_items (category_id, title, item_type, description, address, hours, sort_order) values
(3, 'Classes at The Pilates Barre', 'location', 'Open to staff, volunteers, spouses, and children over the age of 13.', '1905 Notre Dame Blvd., Ste. 170, Chico 95928', 'Saturdays · 10:45 AM', 1);
insert into fitness_items (category_id, title, item_type, content, sort_order) values
(3, 'About Yoga 911 & Danyel Hurd', 'info', 'Danyel Hurd is a Registered Emergency Dept. Nurse and founder of Yoga.911, previously a Field Medic and Nurse in the US Army. The mission of Yoga.911 is to increase awareness of the power of yoga and meditation by educating a network of professionals to share evidence-based practices. Yoga.911 is an integrative, adaptive, and comprehensive practice designed for all students and all levels.', 2);

-- Fight Forward (category 4)
insert into fitness_items (category_id, title, item_type, description, address, hours, website, sort_order) values
(4, 'Fight Forward — Chico', 'location', 'Open to all agency staff. No need to schedule — classes are drop-in Monday through Friday.', 'Chico, CA', 'Drop-in · Mon–Fri', 'https://www.fightforwardchico.com/#our-story', 1);

-- Lord's Gym (category 5)
insert into fitness_items (category_id, title, item_type, description, address, website, sort_order) values
(5, 'Lord''s Gym', 'location', 'Drop-in sessions available for all agency staff. Please identify yourself as an agency staff member when checking in.', '2120 Bird St., Oroville', 'https://www.lordsgymoroville.org/', 1);

-- Acupuncture (category 6)
insert into fitness_items (category_id, title, item_type, description, address, phone, sort_order) values
(6, 'American Chi Center for Health', 'location', 'All staff can receive up to 4 acupuncture sessions per year. Call to schedule.', 'Chico, CA', '(530) 342-2895', 1);

-- North Rim CrossFit (category 7)
insert into fitness_items (category_id, title, item_type, content, sort_order) values
(7, 'How to Get Started', 'info', 'Step 1: Visit northrimcrossfit.com and sign up for a "No-Sweat" intro. Step 2: Meet with one of our coaches. Step 3: Start working out! Drop-in costs are covered for agency staff. NRCF also offers special rates for Public Safety spouses and families.', 1);
insert into fitness_items (category_id, title, item_type, description, address, hours, website, sort_order) values
(7, 'North Rim CrossFit', 'location', 'Specialized programming for first responders. All coaches hold CrossFit Level 1, Level 2, or Olympic Weightlifting certifications.', 'Chico, CA', 'Mon–Fri · 5:00 AM–6:45 PM · Sat 9:00–11:00 AM', 'https://www.northrimcrossfit.com/schedule', 2);

-- Elevate (category 8)
insert into fitness_items (category_id, title, item_type, description, address, hours, phone, sort_order) values
(8, 'Elevate Health and Performance', 'location', 'Group workout functional fitness gym offering CrossFit-style workouts with a focus on injury prevention. Text or call before your first class.', '797 Elliott Rd, Ste K, Paradise, CA 95969', 'Mon–Fri · 5:00 AM · 6:00 AM · 9:00 AM · 10:00 AM · 4:00 PM', '(209) 642-9448', 1);

-- Perspire (category 9)
insert into fitness_items (category_id, title, item_type, content, sort_order) values
(9, 'Booking & Rates', 'info', 'Agency staff are eligible for up to 8 sessions at no cost. After 8 sessions: $20 per session. Spouses of first responders can also utilize this benefit at $20 per session. Call to book and mention the Wellness Unit to receive these rates.', 1);
insert into fitness_items (category_id, title, item_type, description, address, phone, sort_order) values
(9, 'Perspire Sauna Studio — Chico', 'location', 'Private infrared sauna suites with medical-grade red light therapy. Regular sauna use can help reduce stress, improve sleep, support muscle recovery, boost circulation, and promote overall well-being.', 'Chico, CA', '(530) 861-6134', 2);


-- ── CRISIS CONTACTS ───────────────────────────────────────────
insert into crisis_contacts (name, phone, description, sort_order) values
('National Suicide Prevention Lifeline', '988',           'Call or text 988. Available 24/7.',                                         1),
('Crisis Text Line',                     'Text HOME to 741741', 'Free, 24/7 crisis counseling via text.',                             2),
('First Responder Support Network',      '415-462-2227',  'Confidential support for first responders and their families.',              3),
('BCSO Employee Assistance Program',     'Contact HR',    'Contact your agency HR for EAP resources.',                                 4),
('Safe Call Now',                        '1-206-459-3020','Confidential crisis referral service for public safety employees.',         5);
